name: Build container

on: [push, workflow_dispatch, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up BuildKit
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build the image
        run: |
          docker buildx build --push \
            --build-arg VERSION=8.11.3 \
            --build-arg BRANCH=8.11 \
            --tag "${{ secrets.DOCKER_TAG }}:latest" \
            --tag "${{ secrets.DOCKER_TAG }}:8.11.3" \
            --tag "${{ secrets.DOCKER_TAG }}:8.11" \
            --tag "${{ secrets.DOCKER_TAG }}:8" \
            --platform linux/amd64,linux/arm64 .
